### ISSUE TITLE
marked-element removing elements when in a paper-dialog-scrollable

### ISSUE THREAD

**Issue by benmiller86** [PolymerElements/marked-element#48] opened 2017-02-23 09:58 UTC
### Description
If I put the `<marked-element>` in a `<paper-dialog-scrollable>` element it removes any elements I put after the close of the scrollable element and before the close of the containing `<paper-dialog>`. 

If I remove the `<script>` tags from the `<marked-element>` nothing is removed, but obviously I don't get my markdown rendered.

### Example

```
    <paper-icon-button onclick="testDialog.open()" icon="help-outline"></paper-icon-button>
    <paper-dialog id="testDialog">
        <h2>Title</h2>
        <paper-dialog-scrollable>
            <marked-element>
                <div class="markdown-html"></div>
                <script type="text/markdown">
                    ### This is my markdown!!!
                </script>
            </marked-element>
        </paper-dialog-scrollable>
        <div>I will be removed</div>
    </paper-dialog>
```

This is the resulting DOM, notice that the `<div>I will be removed</div>` has been... removed!

![image](https://cloud.githubusercontent.com/assets/1785981/23254057/a1e8a4a4-f9ae-11e6-9c90-8c39d089125e.png)

I have tried wrapping the `<marked-element>` in various other elements to see if I could "contain" the removal as a work around but have had no luck with that.

**Comment by FredKSchott** [comment] 2017-02-24 05:09
Wow... that is very strange. @notwaldorf any idea how this could be happening?

**Comment by stramel** [comment] 2017-03-31 21:20
Hmmmmm not seeing this behavior, https://jsfiddle.net/stramel/5qutwLd0/

@benmiller86 Can you provide a jsfiddle to reproduce this?

**Comment by stramel** [comment] 2017-05-26 14:19
@FredKSchott @e111077  Are you good with closing this? I was unable to reproduce with the jsfiddle above.

**Comment by e111077** [comment] 2017-06-06 22:25
I cannot reproduce either. I just want a second opinion from @valdrinkoshi

**Comment by stramel** [comment] 2017-10-10 15:25
Circling back to this, @valdrinkoshi did you get a chance to look at this?

**Comment by valdrinkoshi** [comment] 2017-10-10 18:18
I've tested this with paper-dialog v2.0.0 in both variants (polymer 1.x and 2.x, webcomponentsjs v0.7.4 and v1.0.0), and I couldn't reproduce this. I've tested on Chrome and Firefox. 
Closing this for now, @benmiller86 let us know if the problem persists for you 👌

**Closed as completed by valdrinkoshi** 2017-10-10 18:18 UTC
